import { NextResponse } from 'next/server';
import { createAdminClient } from '@/lib/supabase/admin';

function isAutoGeneratedEmail(email: string) {
  return /^student_[a-z0-9._+-]+@sanjivani\.edu\.in$/i.test(email.trim());
}

function isValidEmail(email: string) {
  return /^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(email.trim());
}

/**
 * Update a student's login email (Auth + profiles).
 * Used when replacing auto-generated campus emails with real Gmail.
 */
export async function POST(request: Request) {
  try {
    const body = await request.json();
    const userId = (body.userId || '').toString().trim();
    const prn = (body.prn || '').toString().trim().toUpperCase();
    const email = (body.email || '').toString().trim().toLowerCase();

    if (!email || !isValidEmail(email)) {
      return NextResponse.json(
        { success: false, error: 'Please enter a valid Gmail / email address.' },
        { status: 400 }
      );
    }

    if (isAutoGeneratedEmail(email)) {
      return NextResponse.json(
        { success: false, error: 'Use your real Gmail — auto-generated campus emails are not allowed.' },
        { status: 400 }
      );
    }

    if (!userId && !prn) {
      return NextResponse.json(
        { success: false, error: 'User id or PRN is required.' },
        { status: 400 }
      );
    }

    const admin = createAdminClient();
    if (!admin) {
      return NextResponse.json(
        { success: false, error: 'Server auth is not configured.' },
        { status: 503 }
      );
    }

    let profile: { id: string; email: string | null; prn: string | null; full_name: string | null } | null = null;

    if (userId && /^[0-9a-f-]{36}$/i.test(userId)) {
      const { data } = await admin
        .from('profiles')
        .select('id, email, prn, full_name')
        .eq('id', userId)
        .maybeSingle();
      profile = data;
    }

    if (!profile && prn) {
      const { data } = await admin
        .from('profiles')
        .select('id, email, prn, full_name')
        .ilike('prn', prn)
        .maybeSingle();
      profile = data;
    }

    if (!profile) {
      return NextResponse.json(
        { success: false, error: 'Student profile not found. Please sign in again.' },
        { status: 404 }
      );
    }

    // Ensure email not taken by another account
    const { data: clash } = await admin
      .from('profiles')
      .select('id')
      .ilike('email', email)
      .neq('id', profile.id)
      .maybeSingle();
    if (clash) {
      return NextResponse.json(
        { success: false, error: 'This email is already used by another account.' },
        { status: 409 }
      );
    }

    const { error: authErr } = await admin.auth.admin.updateUserById(profile.id, {
      email,
      email_confirm: true,
      user_metadata: {
        email,
      },
    });

    if (authErr) {
      return NextResponse.json(
        { success: false, error: authErr.message || 'Failed to update auth email.' },
        { status: 400 }
      );
    }

    const { error: profileErr } = await admin
      .from('profiles')
      .update({ email })
      .eq('id', profile.id);

    if (profileErr) {
      return NextResponse.json(
        { success: false, error: profileErr.message || 'Failed to update profile email.' },
        { status: 400 }
      );
    }

    return NextResponse.json({
      success: true,
      message: 'Gmail saved successfully.',
      data: {
        id: profile.id,
        email,
        prn: profile.prn,
        full_name: profile.full_name,
      },
    });
  } catch (err: any) {
    return NextResponse.json(
      { success: false, error: err.message || 'Failed to update email.' },
      { status: 500 }
    );
  }
}
