import { NextResponse } from 'next/server';
import { createClient } from '@supabase/supabase-js';
import { createAdminClient } from '@/lib/supabase/admin';
import { appendStudentUser } from '@/lib/google-sheets';

const SUPABASE_URL = process.env.NEXT_PUBLIC_SUPABASE_URL || 'https://ylweomuodekukjjpjrgx.supabase.co';
const SUPABASE_ANON =
  process.env.NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY ||
  process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY ||
  '';

function isAutoGeneratedEmail(email: string) {
  return /^student_[a-z0-9._+-]+@sanjivani\.edu\.in$/i.test(email.trim());
}

function isValidEmail(email: string) {
  return /^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(email.trim());
}

export async function POST(request: Request) {
  try {
    const body = await request.json();
    const { prn, password, fullName, phone, email } = body;

    const cleanPrn = (prn || '').toString().trim().toUpperCase();
    const cleanName = (fullName || '').toString().trim();
    const cleanPass = (password || '').toString();
    const cleanPhone = phone ? String(phone).trim() : '';
    const cleanEmail = (email || '').toString().trim().toLowerCase();

    if (!cleanPrn || !cleanPass || !cleanName) {
      return NextResponse.json(
        { success: false, error: 'Full name, PRN, and password are required.' },
        { status: 400 }
      );
    }

    if (!cleanEmail || !isValidEmail(cleanEmail)) {
      return NextResponse.json(
        { success: false, error: 'Please enter a valid Gmail / email address.' },
        { status: 400 }
      );
    }

    if (isAutoGeneratedEmail(cleanEmail)) {
      return NextResponse.json(
        { success: false, error: 'Use your real Gmail — auto-generated campus emails are not allowed.' },
        { status: 400 }
      );
    }

    if (cleanPass.length < 4) {
      return NextResponse.json(
        { success: false, error: 'Password must be at least 4 characters.' },
        { status: 400 }
      );
    }

    const admin = createAdminClient();
    if (!admin) {
      return NextResponse.json(
        { success: false, error: 'Server auth is not configured. Missing SUPABASE_SERVICE_ROLE_KEY.' },
        { status: 503 }
      );
    }

    // Block duplicate PRN
    const cleanNoZero = cleanPrn.replace(/^0+/, '');
    const { data: byPrn } = await admin
      .from('profiles')
      .select('id, prn, email, full_name')
      .ilike('prn', cleanPrn)
      .maybeSingle();

    let existing = byPrn;
    if (!existing && cleanNoZero && cleanNoZero !== cleanPrn) {
      const { data: alt } = await admin
        .from('profiles')
        .select('id, prn, email, full_name')
        .ilike('prn', cleanNoZero)
        .maybeSingle();
      existing = alt;
    }

    if (existing) {
      return NextResponse.json(
        { success: false, error: `An account for PRN ${cleanPrn} already exists. Please Sign In.` },
        { status: 409 }
      );
    }

    // Block duplicate email
    const { data: byEmail } = await admin
      .from('profiles')
      .select('id, email')
      .ilike('email', cleanEmail)
      .maybeSingle();
    if (byEmail) {
      return NextResponse.json(
        { success: false, error: 'This email is already registered. Please Sign In.' },
        { status: 409 }
      );
    }

    const { data: created, error: createError } = await admin.auth.admin.createUser({
      email: cleanEmail,
      password: cleanPass,
      email_confirm: true,
      user_metadata: {
        full_name: cleanName,
        prn: cleanPrn,
        phone: cleanPhone,
        role: 'student',
      },
    });

    if (createError || !created.user) {
      const msg = createError?.message || 'Failed to create account.';
      if (/already|registered|exists/i.test(msg)) {
        return NextResponse.json(
          { success: false, error: 'An account with this email already exists. Please Sign In.' },
          { status: 409 }
        );
      }
      return NextResponse.json({ success: false, error: msg }, { status: 400 });
    }

    const userId = created.user.id;

    await admin.from('profiles').upsert({
      id: userId,
      email: cleanEmail,
      full_name: cleanName,
      prn: cleanPrn,
      phone: cleanPhone || null,
      role: 'student',
      is_active: true,
    });

    appendStudentUser({
      name: cleanName,
      prn: cleanPrn,
      email: cleanEmail,
      password: cleanPass,
      phone: cleanPhone,
    }).catch(() => {});

    let accessToken: string | null = null;
    let refreshToken: string | null = null;
    if (SUPABASE_ANON) {
      const anon = createClient(SUPABASE_URL, SUPABASE_ANON);
      const { data: sessionData } = await anon.auth.signInWithPassword({
        email: cleanEmail,
        password: cleanPass,
      });
      accessToken = sessionData.session?.access_token ?? null;
      refreshToken = sessionData.session?.refresh_token ?? null;
    }

    const studentRecord = {
      id: userId,
      prn: cleanPrn,
      full_name: cleanName,
      email: cleanEmail,
      role: 'student' as const,
    };

    const cookiePayload = encodeURIComponent(JSON.stringify(studentRecord));
    const response = NextResponse.json({
      success: true,
      message: 'Account created successfully!',
      student: studentRecord,
      session: accessToken && refreshToken ? { access_token: accessToken, refresh_token: refreshToken } : null,
    });

    response.cookies.set('foodline_student_session', cookiePayload, {
      path: '/',
      maxAge: 60 * 60 * 24 * 7,
      sameSite: 'lax',
      httpOnly: false,
    });

    return response;
  } catch (err: any) {
    return NextResponse.json(
      { success: false, error: err.message || 'Failed to create student account.' },
      { status: 500 }
    );
  }
}
